package main

import "fmt"

func main() {
	fmt.Println("===== variables =====")
	variables()
	fmt.Println("===== strings =====")
	stringsGo()
	// fmt.Println("===== numeros =====")
	// numerosGo()
	fmt.Println("===== math =====")
	mathGo()
	// fmt.Println("===== booleanos =====")
	// booleanosGo()
	// fmt.Println("===== arrays =====")
	// arraysGo()
	// fmt.Println("===== slices =====")
	// slicesGo()
	fmt.Println("=====  bucles for =====")
	buclesFor()
	// fmt.Println("===== condiciones if =====")
	// condicionesIf()
	fmt.Println("===== operadores logicos =====")
	operadoresLogicos()
	fmt.Println("===== switch =====")
	switchEnGO()
	// fmt.Println("===== funciones =====")
	// funcionesEnGo()
	// fmt.Println("=====  recursividad =====")
	// recursividadGo()
	// fmt.Println("=====  defer =====")
	// deferGo()
	// fmt.Println("=====  panic y recover =====")
	// panicYRecover()
	fmt.Println("=====  keywords =====")
	keywordsEnGo()
	fmt.Println("=====  estructuras de datos =====")
	arrayEnGo()
	fmt.Println("=====  maps =====")
	mapsEnGo()
	fmt.Println("===== structs =====")
	structsGo()
	// fmt.Println("=====  métodos =====")
	// metodosEnGo()
	// fmt.Println("===== embebido =====")
	// embebidoEnGo()
	fmt.Println("===== modificadores de acceso =====")
	modificadoresAcceso()
	fmt.Println("===== punteros =====")
	punterosGo()
	fmt.Println("===== stringers =====")
	stringersGo()
	fmt.Println("===== concurrencia =====")
	interfacesEnGo()
	fmt.Println("===== concurrencia =====")
	concurrenciaEnGo()
	fmt.Println("===== canales =====")
	channelsGo()
	fmt.Println("===== canales avanzados =====")
	channelsAvanzadosgo()

}
